name: Python application test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.17
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.17"
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Run tests
        run: |
          pytest
